[package]
name = "image-rs-png-bug-20191106"
version = "0.1.0"
authors = ["Andrew Champion <andrew.champion@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22"